import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import EmailSubscription from "@/components/EmailSubscription";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <Navbar />

        {children}

        <EmailSubscription />
        <Footer />
      </body>
    </html>
  );
}
